### ISSUE TITLE
logs printed twice

### ISSUE THREAD

**Issue by little-dude** [nose-devs/nose2#231]
I'm not sure if this is a bug or if I'm just misunderstanding something.

Here is a simple example : 

```python
# test.py
import logging

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(logging.Formatter('%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s'))
log = logging.getLogger(__name__)
log.addHandler(stream_handler)
log.setLevel(logging.INFO)


def fun_test():
    log.info('Running fun_test !')
```

```
$ nose2 test
2015-01-02 11:00:30,421 :: INFO :: test :: Running test_foo!          
INFO:test:Running test_foo!                                           
.                                                                     
----------------------------------------------------------------------
Ran 1 test in 0.000s                                                  
                                                                      
OK                                                                    
```

How can I have the logs printed only once ? There is a doc about the `logcapture` plugin which provides a `--log-capture` option, but the option is not available :

```
$ nose2 -h
usage: nose2 [-s START_DIR] [-t TOP_LEVEL_DIRECTORY] [--config [CONFIG]]
             [--no-user-config] [--no-plugins] [--plugin PLUGINS]
             [--exclude-plugin EXCLUDE_PLUGINS] [--verbose] [--quiet]
             [--log-level LOG_LEVEL] [-B] [-D] [--coverage PATH]
             [--coverage-report TYPE] [--coverage-config FILE] [-C] [-F] [-h]
             [testNames [testNames ...]]

positional arguments:
  testNames

optional arguments:
  -s START_DIR, --start-dir START_DIR
                        Directory to start discovery ('.' default)
  -t TOP_LEVEL_DIRECTORY, --top-level-directory TOP_LEVEL_DIRECTORY, --project-directory TOP_LEVEL_DIRECTORY
                        Top level directory of project (defaults to start dir)
  --config [CONFIG], -c [CONFIG]
                        Config files to load, if they exist. ('unittest.cfg'
                        and 'nose2.cfg' in start directory default)
  --no-user-config      Do not load user config files
  --no-plugins          Do not load any plugins. Warning: nose2 does not do
                        anything if no plugins are loaded
  --plugin PLUGINS      Load this plugin module.
  --exclude-plugin EXCLUDE_PLUGINS
                        Do not load this plugin module
  --verbose, -v         print test case names and statuses
  --quiet
  --log-level LOG_LEVEL
                        Set logging level for message logged to console.
  -h, --help            Show this help message and exit

plugin arguments:
  Command-line arguments added by plugins:

  -B, --output-buffer   Enable output buffer
  -D, --debugger        Enter pdb on test fail or error
  --coverage PATH       Measure coverage for filesystem path (multi-allowed)
  --coverage-report TYPE
                        Generate selected reports, available types: term,
                        term-missing, annotate, html, xml (multi-allowed)
  --coverage-config FILE
                        Config file for coverage, default: .coveragerc
  -C, --with-coverage   Turn on coverage reporting
  -F, --fail-fast       Stop the test run after the first error or failure
```

Even when I explicitely load it, the option is not here : 

```
$ nose2 --plugin nose2.plugins.logcapture --log-capture test
usage: nose2 [-s START_DIR] [-t TOP_LEVEL_DIRECTORY] [--config [CONFIG]]
             [--no-user-config] [--no-plugins] [--plugin PLUGINS]
             [--exclude-plugin EXCLUDE_PLUGINS] [--verbose] [--quiet]
             [--log-level LOG_LEVEL] [-B] [-D] [--coverage PATH]
             [--coverage-report TYPE] [--coverage-config FILE] [-C] [-F] [-h]
             [testNames [testNames ...]]
nose2: error: Unrecognized arguments: --log-capture
```

**Comment by kurniliya** [comment]
I've just spent a good deal of time trying to understand why `--log-capture` may be missing. 

@little-dude Please correct me if I'm wrong: `--log-capture` option is not available if, and only if, current working directory (the one you call `nose2` from) is nose2's source root. Is this so?

The reason for this behavior is that we have there `unittest.cfg` that makes log capture plugin to be loaded by default. In this case there's no need for explicit activation of the plugin via command line switch.

@thedrow Any ideas on why there is such a config right in the root of the sources?

**Comment by little-dude** [comment]
Thanks for looking at my problem @kurniliya. Indeed, the option disappears if in the current directory I have a `unittest.cfg` with 

```
[log-capture]
always-on = True
clear-handlers = False
date-format = None
filter = -nose
log-level = DEBUG
```

If I remove the file or replace `always-on = True` by `always-on = False`, the option re-appears.
I re-did the tests with this in mind : 

```python

# test.py
import logging

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(logging.Formatter('%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s'))
log = logging.getLogger(__name__)
log.addHandler(stream_handler)
log.setLevel(logging.INFO)


def fun_test():
    log.info('Running fun_test !')
```

```
$ cat unittest.cfg
[log-capture]
always-on = True
clear-handlers = True
date-format = None
filter = -nose
log-level = DEBUG

 $ nose2 --verbose
test.FunctionTestCase (test_foo) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

```
$ cat unittest.cfg
[log-capture]
always-on = False
clear-handlers = True
date-format = None
filter = -nose
log-level = DEBUG

$ nose2 --verbose
test.FunctionTestCase (test_foo) ... 2015-01-04 18:50:34,219 :: INFO :: test :: Running test_foo!
INFO:test:Running test_foo!
ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

**Comment by thedrow** [comment]
Not sure if it's a bug or misconfiguration yet. I'll have to try myself.
@little-dude Can you share a project that demonstrates the problem?
@kurniliya I don't know why the source root contains the unittest.cfg file.

**Comment by kurniliya** [comment]
@thedrow Maybe we could remove this `unittest.cfg` from the source root then? Assuming that all the tests would stay "green" after doing that, of course.
@little-dude Thanks, it becomes more clear. All but the main issue ("...to have the logs once...") can be answered now, I guess.

*>If I remove the file or replace always-on = True by always-on = False, the option re-appears.*
AFAIK, that's how it should be. No need for command line option activating a plugin if the plugin is already activated in config. But looks like this, indeed, may be confusing...

*>With log-capture enabled : I don't see logs at all.*
Makes sense. As per log capture plugin's [docs](https://nose2.readthedocs.org/en/latest/plugins/logcapture.html): 
> Capture log messages during test execution, appending them to the error reports of failed tests.

And `fun_test` in the exapmle doesn't fail -- it passes. With log capture enabled, do you need to see logs captured during execution of passed tests? If yes, why?

**Comment by thedrow** [comment]
@kurniliya We can either do that or exclude it from the distribution using the MANIFEST.in file.
I think I prefer the latter.

**Comment by little-dude** [comment]
Sorry guys, I had very little time this week. Thanks a lot for your help on this.

> @little-dude Thanks, it becomes more clear. All but the main issue ("...to have the logs once...") can be answered now, I guess.

Yeah, thanks for the clarification.

> With log capture enabled, do you need to see logs captured during execution of passed tests? If yes, why?

Yes I'd like to. I'm testing an SDN solution, and I often have dependencies between my tests. For example : 
   * setup
   * test dhcp
   * test ping <= This requires dhcp to be correctly configured. But if dhcp test passes and this fails, I'll probably need to look at dhcp logs to debug.

> @little-dude Can you share a project that demonstrates the problem?

```python

# test.py
import logging

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(logging.Formatter(
    '%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s'))
log = logging.getLogger(__name__)
log.addHandler(stream_handler)
log.setLevel(logging.INFO)


def test_foo():
    log.info('Running test_foo!')


def test_bar():
    log.info('Running test_bar!')
    raise Exception
```

```
$ nose2
2015-01-10 15:06:34,282 :: INFO :: test :: Running test_bar!
INFO:test:Running test_bar!
E2015-01-10 15:06:34,282 :: INFO :: test :: Running test_foo!
INFO:test:Running test_foo!
.
======================================================================
ERROR: test.FunctionTestCase (test_bar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/littledude/issuenose2/test.py", line 17, in test_bar
    raise Exception
Exception

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
```

What I'm actually expecting is the behavious `nose` has : print the logs, *and* capture them : 

```
$ nosetest
2015-01-10 15:08:18,581 :: INFO :: test :: Running test_foo!
.2015-01-10 15:08:18,581 :: INFO :: test :: Running test_bar!
E
======================================================================
ERROR: test.test_bar
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/littledude/env2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/littledude/issuenose2/test.py", line 17, in test_bar
    raise Exception
Exception: 
-------------------- >> begin captured logging << --------------------
test: INFO: Running test_bar!
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
```

**Comment by little-dude** [comment]
Btw, I just noticed the stacktrace is much clearer with `nose2`, great job :+1:

**Comment by little-dude** [comment]
Any idea what could cause that ? I've been looking at the source code, and I don't see anything weird being done with logging. Do you have any clue to help me to start working on this ?

**Comment by thedrow** [comment]
I haven't looked into it yet.

**Comment by little-dude** [comment]
I've been able to workaround the problem. In nose2, the loggers you define in your test modules are children of the root logger, defined in `main.py`. By default, those children propagate their messages to their parents, which causes this duplicate output. Two solution : 

* let `logger` handle that automatically with `Logger.basicConfig`.
* manually handle that by setting the `propagate` attribute of the test modules loggers to `False`.

### With basicConfig() :

```python

# test.py                                                      
import logging                                                              

log = logging.getLogger(__name__)
logging.basicConfig()

def test_foo():
    log.info('Running test_foo!')
  
def test_bar():                       
    log.info('Running test_bar!')
    raise Exception
```

Now I only hove nose2 root logger logs : 

```
$ nose2 --log-level INFO
INFO:test:Running test_bar!
EINFO:test:Running test_foo!
.
======================================================================
ERROR: test.FunctionTestCase (test_bar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/corentih/pygash/pygash/tests/test.py", line 22, in test_bar
    raise Exception
Exception

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
```


It's good but that means that nose2 logger's config prevails over my module logging config. Thus, whatever parameters I give to `basicConfig`, they won't apply : 

```python 
# test.py                                                      
import logging                                                              

log = logging.getLogger(__name__)
logging.basicConfig(format='%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s')

def test_foo():
    log.info('Running test_foo!')
  
def test_bar():                       
    log.info('Running test_bar!')
    raise Exception
```

Output : 

```
$ nose2 --log-level INFO
INFO:test:Running test_bar!
EINFO:test:Running test_foo!
.
======================================================================
ERROR: test.FunctionTestCase (test_bar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/corentih/pygash/pygash/tests/test.py", line 22, in test_bar
    raise Exception
Exception

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
```

This is not what I want because for debugging purposes, I may want to have certain modules with loglevel set to DEBUG of example.

### With Logger.propagate
```python

# test.py                                                      
import logging                                                              

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(logging.Formatter('%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s'))
log = logging.getLogger(__name__)
log.addHandler(stream_handler)
log.setLevel(logging.INFO)
log.propagate = False

def test_foo():
    log.info('Running test_foo!')
  
def test_bar():                       
    log.info('Running test_bar!')
    raise Exception
```

Output : 

```
2015-02-20 19:13:27,481 :: INFO :: test :: Running test_bar!
E2015-02-20 19:13:27,481 :: INFO :: test :: Running test_foo!
.
======================================================================
ERROR: test.FunctionTestCase (test_bar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/corentih/pygash/pygash/tests/test.py", line 23, in test_bar
    raise Exception
Exception

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
```

Wohoo!

### Remaining issues

I see two drawbacks to the previous solutions : 
* that breaks log-capture, because the loggers to send their messages back to the root logger
* if I use external modules that I didn't write myself, I have to configure their loggers as well, otherwise, their output will be duplicated too. See the below example : 


```python
# blah.py

import logging
stream_handler = logging.StreamHandler()
log = logging.getLogger(__name__)       
log.addHandler(stream_handler)          
log.setLevel(logging.DEBUG)             
                                        
def say_blah():                         
    log.info('BLAAAAAAH!!!')            
```

```python 
# test.py

import logging                                                 
import blah                                                    
                                                               
stream_handler = logging.StreamHandler()                       
stream_handler.setFormatter(logging.Formatter(                 
    '%(asctime)s :: %(levelname)s :: %(name)s :: %(message)s'))
log = logging.getLogger(__name__)                              
log.addHandler(stream_handler)                                 
log.setLevel(logging.INFO)                                     
log.propagate = False                                          
                                                               
# log = logging.getLogger(__name__)                            
# logging.basicConfig()                                        
                                                               
                                                               
def test_foo():                                                
    # blah.say_blah()                                          
    log.info('Running test_foo!')                              
                                                               
                                                               
def test_bar():                                                
    log.info('Running test_bar!')                              
    raise Exception                                            
```

Output : 

```
2015-02-20 19:37:38,112 :: INFO :: test :: Running test_bar!
EBLAAAAAAH!!!
INFO:blah:BLAAAAAAH!!!
2015-02-20 19:37:38,112 :: INFO :: test :: Running test_foo!
.
======================================================================
ERROR: test.FunctionTestCase (test_bar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/corentih/pygash/pygash/tests/test.py", line 24, in test_bar
    raise Exception
Exception

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
```

Now, how can I force all the loggers of the libs I import to use `Logger.propragate = False` ?

**Comment by little-dude** [comment]
I forgot about this issue but I think we can close it. The solution to me "problem" is to [set the the clear-handlers option to True](http://nose2.readthedocs.org/en/latest/plugins/logcapture.html#configvar-clear-handlers). When doing so, nose remove the hanlders from every loggers it finds. Then, the loggers send their messages to nose2 root logger, which prints them once.

It's actually much better than configuring a handler in every module.
