### ISSUE TITLE
exception when using layers with testtools result class

### ISSUE THREAD

**Issue by little-dude** [nose-devs/nose2#280]
```
Traceback (most recent call last):
  File "[...]/custom_repos/nose2/nose2/main.py", line 271, in runTests
    self.result = runner.run(self.test)
  File "[...]/custom_repos/nose2/nose2/runner.py", line 53, in run
    executor(test, result)
  File "[...]/lib/python2.7/site-packages/pygash/plugins/testtools_.py", line 115, in executor
    return suite.run(result)
  File "[...]/lib/python2.7/site-packages/unittest2/suite.py", line 126, in run
    test(result)
  File "[...]/lib/python2.7/site-packages/unittest2/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "[...]/custom_repos/nose2/nose2/suite.py", line 27, in run
    self.handle_previous_test_teardown(result)
  File "[...]/custom_repos/nose2/nose2/suite.py", line 56, in handle_previous_test_teardown
    delattr(result, '_previousTestClass')
AttributeError: _previousTestClass
```

seems that `_previousTestClass` is a class attribute, which is why we cannot delete it at the instance level. Weirdly, the result class directly inheritates from the `unittest` one, so we _should_ also see this issue in our tests:

```python
class TestResult(unittest.TestResult):
    # [...]
```

**Comment by little-dude** [comment]
note: this is only on master.
