### ISSUE TITLE
MySQL Error 1040: Too many connections When Running Tests in Parallel with Multiple Processes

### ISSUE THREAD

**Issue by ye** [nose-devs/nose2#292]
I was trying to run tests in parallel with `mp` plugin (to speed up test runtime). But it failed quickly with a bunch of MySQL 1040 errors (Too many connections). Any pointers what was happening?

I am running a Debian Virtualbox VM on OS X El Capitan with these settings:

```
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
```

Shell output below:

``` bash
$ uname -a
Linux 26119ae620ce 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
$ python -V
Python 3.4.4
$ pip freeze | grep nose2
nose2==0.6.4

$ tree /api/tests
/api/tests
├── __init__.py
├── base.py
├── mock_data.py
├── requirements.txt
├── test_auth.py
├── test_error_handler.py
├── test_users.py
└── tools.py

1 directory, 3 files

$ cd /api/ && nose2 --plugin=nose2.plugins.mp -N 2
...
======================================================================
ERROR: test_auth_authenticated (api.tests.test_auth.AuthenticationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 837, in _connect
    self._get_server_information()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1048, in _get_server_information
    packet = self._read_packet()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.OperationalError: (1040, 'Too many connections')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/api/tests/test_auth.py", line 79, in setUp
    super().setUp()
  File "/api/tests/base.py", line 224, in setUp
    db.drop_all()
  File "/usr/local/lib/python3.4/site-packages/flask_sqlalchemy/__init__.py", line 903, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/usr/local/lib/python3.4/site-packages/flask_sqlalchemy/__init__.py", line 887, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 3458, in drop_all
    tables=tables)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1725, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1718, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1908, in contextual_connect
    self.pool.connect(),
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 342, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 652, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 444, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 1078, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 289, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 415, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/pool.py", line 546, in __connect
    connection = self.__pool._creator()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.4/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 837, in _connect
    self._get_server_information()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1048, in _get_server_information
    packet = self._read_packet()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.OperationalError: (OperationalError) (1040, 'Too many connections') None None

----------------------------------------------------------------------
Ran 481 tests in 107.407s

FAILED (failures=33, errors=439)
```

And there were approximately 274 concurrent connections at the peak of the test run.
![screen shot 2016-05-06 at 3 07 10 pm](https://cloud.githubusercontent.com/assets/133924/15083959/6332b912-139e-11e6-9da0-c4135713857d.png)

**Comment by little-dude** [comment]
Hi,

I'm sorry for taking so long to answer.

Can you be more specific about what you think the issue is and how it's related to the mp plugin? It's hard to tell what's happening, since I don't know what the application you are testing, and I don't know how your tests are written.

**Comment by ye** [comment]
@little-dude thanks for your response. I don't know exactly how it related to mp plugin either - but they did show up when I use the mp plugin lately. I am thinking it could be a connection pooling leak issue but I have yet to verify. Unfortunately I can't share the test code as most of them are proprietary.

**Comment by little-dude** [comment]
@ptthiem does that ring a bell? I'm not familiar with the MP plugin internals unfortunately.

**Comment by ptthiem** [comment]
Hmm.  We haven't changed the mp plugin very recently, to my knowledge.  Some things I would have to dig a bit on.  Off the top of my head.  If the standard forking behavior is used any code executed on module load, c-module load, or case instantiation would be executed and if that opens a connection would be duplicated in each child process.  Also, tests are loaded/instantiated twice.  Once for discovery and once in the worker process.  The test fixtures should not execute in the master process, and tests sharing a fixture should be sent to the same process, as the process is reused (we create worker processes once).  But I would think that all the TearDown's should be called, assuming there is a way to get the libraries to release connections.   I know the following will sound reaaaly silly, and I apologize.  Are you explicitly calling close on the db connection?   In pycogsys for postgress the with-statement on the connection opens and closes transactions not the connection, I have to explicitly close() to get the connection to go away.  Well just a thought.  Otherwise, at this point I'd be tempted to poke around with PDB (perhaps having to resort to streaming pdb in/out over a socket to someplace).  Are any of those connections associated with the master python process created from the nose2 script or all they all on the worker processes?

**Comment by ye** [comment]
Thanks @ptthiem for chime in! No, I don't have any special setup for closing db connections, which is probably why it's leaking.

As you can see in the stack trace, we use Flask-SQLAlchemy + SQLAlchemy + PyMySQL db driver with MySQL 5.6. After fiddling around with the [connection pooling manager](http://docs.sqlalchemy.org/en/rel_0_9/core/pooling.html#switching-pool-implementations), I discovered that connection pooling was indeed the culprit in that switching to `NullPool` connection pooling manager all tests were able to finish without triggering MySQL 1040 Error.

In SQLAlchemy's documentation, there is a `SingletonThreadPool` that were designed for concurrent setup. Perhaps that will solve the issue here.

PS: there is a bit of [trickery to configure SQLAlchemy for multiprocessing](http://docs.sqlalchemy.org/en/rel_0_9/core/pooling.html#using-connection-pools-with-multiprocessing) as mentioned in the same documentation. But that's probably outside of nose2's scope.

**Comment by katrinabrock** [comment]
Looks like this is resolved. If not, please comment and I will reopen.
