### ISSUE TITLE
Junit-XML test_properties does not work as documented.

### ISSUE THREAD

**Issue by mtnakayama** [nose-devs/nose2#320]
nose2 version 0.6.5

On [http://nose2.readthedocs.io/en/latest/plugins/junitxml.html#configuration-junit-xml](http://nose2.readthedocs.io/en/latest/plugins/junitxml.html#configuration-junit-xml), it says:
 "The default configuration is equivalent to including the following in a `unittest.cfg` file"
```[junit-xml]
always-on = False
keep_restricted = False
path = nose2-junit.xml
test_fullname = False
test_properties = None
```

However, the line `test_properties = None` creates this error:

```FERROR:nose2.main:Internal Error
Traceback (most recent call last):
  File "[[REDACTED]]/jenkinstestproject/venv/local/lib/python2.7/site-packages/nose2/main.py", line 271, in runTests
    self.result = runner.run(self.test)
  File "[[REDACTED]]/jenkinstestproject/venv/local/lib/python2.7/site-packages/nose2/runner.py", line 58, in run
    self.session.hooks.stopTestRun(event)
  File "[[REDACTED]]/jenkinstestproject/venv/local/lib/python2.7/site-packages/nose2/events.py", line 224, in __call__
    result = getattr(plugin, self.method)(event)
  File "[[REDACTED]]/jenkinstestproject/venv/local/lib/python2.7/site-packages/nose2/plugins/junitxml.py", line 129, in stopTestRun
    self._check()
  File "[[REDACTED]]/jenkinstestproject/venv/local/lib/python2.7/site-packages/nose2/plugins/junitxml.py", line 118, in _check
    self.test_properties_path)
IOError: [Errno 2] JUnitXML: Properties file does not exist: '[[REDACTED]]/jenkinstestproject/None'
Internal Error: runTests aborted: [Errno 2] JUnitXML: Properties file does not exist: '[[REDACTED]]/jenkinstestproject/None'
```

**Comment by katrinabrock** [comment]
Could not reproduce. Here is my attempt:
```
 ❯❯❯ rm -rf env
~/nose/320 
 ❯❯❯ virtualenv env
New python executable in ~/nose/320/env/bin/python2
Also creating executable in ~/nose/320/env/bin/python
Installing setuptools, pip, wheel...done.
~/nose/320 
 ❯❯❯ source env/bin/activate
(env) ~/nose/320 
 ❯❯❯ pip install nose2
Collecting nose2
Collecting six>=1.1 (from nose2)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, nose2
Successfully installed nose2-0.6.5 six-1.11.0
(env) ~/nose/320 
 ❯❯❯ python --version
Python 2.7.13
(env) ~/nose/320 
 ❯❯❯ pip --version
pip 9.0.1 from ~/nose/320/env/lib/python2.7/site-packages (python 2.7)
(env) ~/nose/320 
 ❯❯❯ cat test_dummy.py
def test_pass():
    assert True


def test_fail():
    assert False
(env) ~/nose/320 
 ❯❯❯ cat /tmp/myconfig.cfg
[junit-xml]
always-on = False
keep_restricted = False
path = nose2-junit.xml
test_fullname = False
test_properties = None
(env) ~/nose/320 
 ❯❯❯ nose2 --plugin nose2.plugins.junitxml --config /tmp/myconfig.cfg
F.
======================================================================
FAIL: test_dummy.FunctionTestCase (test_fail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbrock/nose/320/test_dummy.py", line 6, in test_fail
    assert False
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
(env) ~/nose/320 
```

**Comment by katrinabrock** [comment]
Feel free to reopen if this is still impacting you. Maybe only an issue on certain versions of python?

**Comment by ptthiem** [comment]
Adding -X to Katrina's command line will reproduce.  The basic problems is that 

"test_properties=None" is not correct.  config.as_str doesn't parse None as None, but the config.as_str default is literally Python's None.

**Comment by artragis** [comment]
It's "kind of" a bug from sphinx extension. I think I can refactor [this loop](https://github.com/nose-devs/nose2/blob/master/nose2/sphinxext.py#L109) to remove "default to None" parameters.

To ensure those parameters are documented, we can add another documentation section "Optional parameters".

**Comment by katrinabrock** [comment]
At this point, IMO probably better to change docs than to change the plugin. Willing to be convinced otherwise.

**Comment by artragis** [comment]
In fact all documentations of config parameters that default to `None` will print "Is equivalent to `parameter = None` and people will not understand why it is not so equivalent.

So I think two possibilities exist : 

- change the "is equivalent to" block display like I proposed
- change the behaviour of as_string so that `parameter = None` is seen as "I put the python `None` value instead of the `"None"` string.
