### ISSUE TITLE
Show parameter of subTest

### ISSUE THREAD

**Issue by IceflowRE** [nose-devs/nose2#334]
```
class NumbersTest(unittest.TestCase):
    def test_even(self):
        """
        Test that numbers between 0 and 5 are all even.
        """
        for i in range(0, 6):
            with self.subTest(i=i):
                self.assertEqual(i % 2, 0)
```
https://docs.python.org/3.6/library/unittest.html

```
======================================================================
FAIL: test_even (__main__.NumbersTest) (i=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_even (__main__.NumbersTest) (i=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_even (__main__.NumbersTest) (i=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0
```

As shown there, it can show the parameter of the subtests, which is not done. However it seems that it stoppes after first fail too.

**Comment by ultimatecoder** [comment]
I am facing the same problem. The bug is Opened from I think one year. Still no one is cared to fix this.

**Comment by k-husmann** [comment]
Just to complete this, this is how it looks using nosetests  version 1.3.7
```
$ nosetests -v test_x.py
Test that numbers between 0 and 5 are all even. ... FAIL

======================================================================
FAIL: Test that numbers between 0 and 5 are all even.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/uia83687/Test/Python/Nasenunit/test_x.py", line 10, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```
In the `FAIL:....`  line is missing the `(i=1)` part.

**Comment by IceflowRE** [comment]
Would it be possible to investigate in this issue more?

**Comment by cpwr** [comment]
we still need that

**Comment by zjjott** [comment]
+1

**Comment by mgrandi** [comment]
+1 

I might look into this if i have time, seems to be just a bug with the 'reporter' plugin, it still seems to run the tests fine

**Comment by stefanholek** [comment]
FYI, I got subtests working on my [334-subtest-support](https://github.com/stefanholek/nose2/tree/334-subtest-support) branch. Still lacks tests though so no PR just yet. 😎
