### ISSUE TITLE
Need to install nose2-html-report when using junitxml plugin

### ISSUE THREAD

**Issue by jamshid** [nose-devs/nose2#340]
Not sure what changed but my previously running tests started failing with this `ImportError` about  `nose2_html_report.html_report`. 

**Adding a `pip install nose2-html-report` seems to fix it.**

```
$ cat /tmp/myconfig.cfg
[junit-xml]
always-on = True
path = /results/test_foo.Test_Foo.test_foo.xml
$ PYTHONPATH=$(pwd) nose2 --plugin nose2.plugins.junitxml --config /tmp/myconfig.cfg
Traceback (most recent call last):
  File "/usr/bin/nose2", line 11, in <module>
    load_entry_point('nose2==0.6.5', 'console_scripts', 'nose2')()
  File "/usr/lib/python2.7/site-packages/nose2/main.py", line 306, in discover
    return main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nose2/main.py", line 100, in __init__
    super(PluggableTestProgram, self).__init__(**kw)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/site-packages/nose2/main.py", line 122, in parseArgs
    self.handleCfgArgs(cfg_args)
  File "/usr/lib/python2.7/site-packages/nose2/main.py", line 199, in handleCfgArgs
    self.loadPlugins()
  File "/usr/lib/python2.7/site-packages/nose2/main.py", line 244, in loadPlugins
    self.session.loadPlugins(self.defaultPlugins, self.excludePlugins)
  File "/usr/lib/python2.7/site-packages/nose2/session.py", line 134, in loadPlugins
    self.loadPluginsFromModule(util.module_from_name(module))
  File "/usr/lib/python2.7/site-packages/nose2/util.py", line 90, in module_from_name
    __import__(name)
ImportError: No module named nose2_html_report.html_report
```

PS: Bummer that this python test library is no longer maintained. It fixed some threading issues I've had with unittest, pytest, and nosetests when tests use `multiprocessing`.

**Comment by katrinabrock** [comment]
Can you post the minimal steps to reproduce this? What is the test you are running?

**Comment by katrinabrock** [comment]
If this issue is is still impacting you, feel free to reopen with more details.
