### ISSUE TITLE
Coverage fail_under not being respected

### ISSUE THREAD

**Issue by robertsben** [nose-devs/nose2#396]
It appears that failure due to coverage percentages was not fully fixed in #389.

[This MR](https://github.com/nose-devs/nose2/pull/395) should illustrate the problem. 

Although using the `--with-coverage` appears to work as expected, using a `nose2.cfg` (or `unittest.cfg` file does not.

When
```
[report]
fail_under = 100
```
is set in `.coveragerc` and 
```
[coverage]
always-on = True
```
is set in `nose2.cfg` nose2 will not return an exit status of 1, even if coverage percentage is below 100%.

After some debugging, it looks like the problem is related to the order in which plugins are run. 

In `nose2.plugins.result.ResultReporter` the `wasSuccessful` function will always set `event.success = True`. If `nose2.plugins.coverage.Coverage.wasSuccessful()` was called before this, whatever result `coverage` reported will be overwritten.

This would also affect any other plugins that utilise a `wasSuccessful` function to set `event.success`, making plugin execution susceptible to race conditions.

Output from the above test run on (`uname -a`) Darwin DEVML0195261 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 using `tox`

```
======================================================================
FAIL: test_run_coverage_fail_under_race_conditions (nose2.tests.functional.test_coverage.TestCoverage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bro13/Documents/SSDM/nose2/nose2/tests/functional/test_coverage.py", line 112, in test_run_coverage_fail_under_race_conditions
    assert_exit_status=1)
  File "/Users/bro13/Documents/SSDM/nose2/nose2/tests/functional/test_coverage.py", line 28, in assertProcOutputPattern
    self.assertEqual(assert_exit_status, proc.poll())
AssertionError: 1 != 0

-------------------- >> begin captured logging << --------------------
nose2.main: DEBUG: logging initialized 30
nose2.session: DEBUG: Loading plugin modules: {'nose2.plugins.debugger', 'nose2.plugins.loader.generators', 'nose2.plugins.result', 'nose2.plugins.loader.parameters', 'nose2.plugins.buffer', 'nose2.plugins.failfast', 'nose2.plugins.logcapture', 'nose2.plugins.dundertest', 'nose2.plugins.loader.loadtests', 'nose2.plugins.loader.functions', 'nose2.plugins.loader.testcases', 'nose2.plugins.loader.testclasses', 'nose2.plugins.loader.discovery', 'nose2.plugins.coverage'}
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.buffer.OutputBufferPlugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.coverage.Coverage'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.coverage.Coverage object at 0x107000be0>
nose2.session: DEBUG: Register method wasSuccessful for plugin <nose2.plugins.coverage.Coverage object at 0x107000be0>
nose2.session: DEBUG: Register method beforeSummaryReport for plugin <nose2.plugins.coverage.Coverage object at 0x107000be0>
nose2.session: DEBUG: Register method afterSummaryReport for plugin <nose2.plugins.coverage.Coverage object at 0x107000be0>
nose2.session: DEBUG: Register method createTests for plugin <nose2.plugins.coverage.Coverage object at 0x107000be0>
nose2.session: DEBUG: Plugin is available: <class 'nose2.events.Plugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.debugger.Debugger'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.dundertest.DunderTestFilter'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.dundertest.DunderTestFilter object at 0x107e54c88>
nose2.session: DEBUG: Register method startTestRun for plugin <nose2.plugins.dundertest.DunderTestFilter object at 0x107e54c88>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.failfast.FailFast'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.discovery.DiscoveryLoader'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.discovery.DiscoveryLoader object at 0x107fb4160>
nose2.session: DEBUG: Register method loadTestsFromNames for plugin <nose2.plugins.loader.discovery.DiscoveryLoader object at 0x107fb4160>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.discovery.DiscoveryLoader object at 0x107fb4160>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.functions.Functions'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.functions.Functions object at 0x107fb4eb8>
nose2.session: DEBUG: Register method loadTestsFromModule for plugin <nose2.plugins.loader.functions.Functions object at 0x107fb4eb8>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.functions.Functions object at 0x107fb4eb8>
nose2.session: DEBUG: Plugin is available: <class 'nose2.events.Plugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.generators.Generators'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.generators.Generators object at 0x107f14358>
nose2.session: DEBUG: Register method loadTestsFromModule for plugin <nose2.plugins.loader.generators.Generators object at 0x107f14358>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.generators.Generators object at 0x107f14358>
nose2.session: DEBUG: Register method loadTestsFromTestCase for plugin <nose2.plugins.loader.generators.Generators object at 0x107f14358>
nose2.session: DEBUG: Register method getTestCaseNames for plugin <nose2.plugins.loader.generators.Generators object at 0x107f14358>
nose2.session: DEBUG: Plugin is available: <class 'nose2.events.Plugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.loadtests.LoadTestsLoader'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.loadtests.LoadTestsLoader object at 0x107f14198>
nose2.session: DEBUG: Register method moduleLoadedSuite for plugin <nose2.plugins.loader.loadtests.LoadTestsLoader object at 0x107f14198>
nose2.session: DEBUG: Register method handleDir for plugin <nose2.plugins.loader.loadtests.LoadTestsLoader object at 0x107f14198>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.parameters.Parameters'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.parameters.Parameters object at 0x107e83470>
nose2.session: DEBUG: Register method loadTestsFromModule for plugin <nose2.plugins.loader.parameters.Parameters object at 0x107e83470>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.parameters.Parameters object at 0x107e83470>
nose2.session: DEBUG: Register method getTestCaseNames for plugin <nose2.plugins.loader.parameters.Parameters object at 0x107e83470>
nose2.session: DEBUG: Plugin is available: <class 'nose2.events.Plugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.testcases.TestCaseLoader'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.testcases.TestCaseLoader object at 0x107e95b38>
nose2.session: DEBUG: Register method loadTestsFromModule for plugin <nose2.plugins.loader.testcases.TestCaseLoader object at 0x107e95b38>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.testcases.TestCaseLoader object at 0x107e95b38>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.loader.testclasses.TestClassLoader'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.loader.testclasses.TestClassLoader object at 0x107fbbe48>
nose2.session: DEBUG: Register method loadTestsFromModule for plugin <nose2.plugins.loader.testclasses.TestClassLoader object at 0x107fbbe48>
nose2.session: DEBUG: Register method loadTestsFromName for plugin <nose2.plugins.loader.testclasses.TestClassLoader object at 0x107fbbe48>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.logcapture.LogCapture'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.events.Plugin'>
nose2.session: DEBUG: Plugin is available: <class 'nose2.plugins.result.ResultReporter'>
nose2.session: DEBUG: Register active plugin <nose2.plugins.result.ResultReporter object at 0x1078db7b8>
nose2.session: DEBUG: Register method startTest for plugin <nose2.plugins.result.ResultReporter object at 0x1078db7b8>
nose2.session: DEBUG: Register method testOutcome for plugin <nose2.plugins.result.ResultReporter object at 0x1078db7b8>
nose2.session: DEBUG: Register method wasSuccessful for plugin <nose2.plugins.result.ResultReporter object at 0x1078db7b8>
nose2.session: DEBUG: Register method afterTestRun for plugin <nose2.plugins.result.ResultReporter object at 0x1078db7b8>
nose2.plugins.coverage: DEBUG: createTests not already handled. coverage should work
nose2.main: DEBUG: Create tests from []/None
```

**Comment by sirosen** [comment]
Thanks for spotting this, and for producing a test case.
I'll try to put together a viable fix to include in #395 , so that we can add that test without breaking `master`

> After some debugging, it looks like the problem is related to the order in which plugins are run.

:cry: I don't think that nose2 should allow this. It's going to lead to more bugs of this flavor, related to plugin load order.
I'm going to open an issue for this, but not try solving it for #395 unless there's no way out.

I hope that we can get `nose2.plugins.result.ResultReporter.wasSuccessful()` to respect a prior value without fixing the underlying plugin load order bug.
Assuming there's a fix which makes it pass, I might want to rename your test in #395, if that's okay.

**Comment by robertsben** [comment]
Yeah, it looks a particularly tricky one to tackle. I sat and thought about it for a while and the best I could come up with was adding a `modified` flag attribute (or similar) to the `ResultSuccessEvent`, but that felt a bit more like duct tape than a proper fix.

By all means make whatever modifications you need to to the test; I wrote it fairly hastily by copying another and modifying it to exemplify the issue.

Thanks for your help!
