### ISSUE TITLE
\n between param items seems to break pretty-assert

### ISSUE THREAD

**Issue by OddBloke** [nose-devs/nose2#433]
When I run this test file:

```py
import unittest

from nose2.tools.params import params


class TestExample(unittest.TestCase):

    @params(('foobar',),
            ('wibble',))
    def test_one(self, value):
        assert not value

    @params(('foobar',), ('wibble',))
    def test_two(self, value):
        assert not value
```

I, confusingly, get different output from each of the tests:

```
$ nose2 --pretty-assert example
FFFF
======================================================================
FAIL: test_one:1
'foobar' (example.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/scratch/example.py", line 11, in test_one
    assert not value
AssertionError

======================================================================
FAIL: test_one:2
'wibble' (example.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/scratch/example.py", line 11, in test_one
    assert not value
AssertionError

======================================================================
FAIL: test_two:1
'foobar' (example.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/scratch/example.py", line 15, in test_two
    assert not value
AssertionError

>>> assert not value

values:
    value = 'foobar'
======================================================================
FAIL: test_two:2
'wibble' (example.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/scratch/example.py", line 15, in test_two
    assert not value
AssertionError

>>> assert not value

values:
    value = 'wibble'
----------------------------------------------------------------------
Ran 4 tests in 0.000s
```

You can see that for `test_two`, I get pretty assert output, but for `test_one` I don't. The only difference between the two definitions is the newline between the example cases.

**Comment by OddBloke** [comment]
Below is a diff of the two test function definitions (taken from the output of `astpretty example.py`). As you can see, the only differences between the two are function name and lineno/col_offset of the various parts:

```diff
--- one	2019-03-21 12:05:41.287971429 -0400
+++ two	2019-03-21 12:05:54.499970204 -0400
@@ -1,11 +1,11 @@
                 FunctionDef(
-                    lineno=8,
+                    lineno=13,
                     col_offset=4,
-                    name='test_one',
+                    name='test_two',
                     args=arguments(
                         args=[
-                            arg(lineno=10, col_offset=17, arg='self', annotation=None),
-                            arg(lineno=10, col_offset=23, arg='value', annotation=None),
+                            arg(lineno=14, col_offset=17, arg='self', annotation=None),
+                            arg(lineno=14, col_offset=23, arg='value', annotation=None),
                         ],
                         vararg=None,
                         kwonlyargs=[],
@@ -15,33 +15,33 @@
                     ),
                     body=[
                         Assert(
-                            lineno=11,
+                            lineno=15,
                             col_offset=8,
                             test=UnaryOp(
-                                lineno=11,
+                                lineno=15,
                                 col_offset=15,
                                 op=Not(),
-                                operand=Name(lineno=11, col_offset=19, id='value', ctx=Load()),
+                                operand=Name(lineno=15, col_offset=19, id='value', ctx=Load()),
                             ),
                             msg=None,
                         ),
                     ],
                     decorator_list=[
                         Call(
-                            lineno=8,
+                            lineno=13,
                             col_offset=5,
-                            func=Name(lineno=8, col_offset=5, id='params', ctx=Load()),
+                            func=Name(lineno=13, col_offset=5, id='params', ctx=Load()),
                             args=[
                                 Tuple(
-                                    lineno=8,
+                                    lineno=13,
                                     col_offset=13,
-                                    elts=[Str(lineno=8, col_offset=13, s='foobar')],
+                                    elts=[Str(lineno=13, col_offset=13, s='foobar')],
                                     ctx=Load(),
                                 ),
                                 Tuple(
-                                    lineno=9,
-                                    col_offset=13,
-                                    elts=[Str(lineno=9, col_offset=13, s='wibble')],
+                                    lineno=13,
+                                    col_offset=26,
+                                    elts=[Str(lineno=13, col_offset=26, s='wibble')],
                                     ctx=Load(),
                                 ),
                             ],
```

**Comment by sirosen** [comment]
😱 Thank you for the detailed bug report!

pretty-assert is limited to some fairly simple and rudimentary inspection of stackframes and, if it can't figure out what's going on, it refrains from decorating the test output.
I think it should probably print something, even if it's just `nose2.plugins.prettyassert error: unable to determine values` so that it's unambiguous that it failed.

I will try to tackle this and queue up a release when I'm able, but am also fearful that it won't be easy. We'll see what happens, I guess.

**Comment by OddBloke** [comment]
My pleasure!  My intuition here is that something is doing some naive line arithmetic and ending up off-by-N because the decorator takes more than a single line, but certainly I agree that *finding* that is likely a tough task. :-)
