### ISSUE TITLE
Using the setup.py test collector causes an error to be raised

### ISSUE THREAD

**Issue by thedrow** [nose-devs/nose2#94]
```
$ python setup.py test
running test
running egg_info
writing nose2_testsuite.egg-info/PKG-INFO
writing top-level names to nose2_testsuite.egg-info/top_level.txt
writing dependency_links to nose2_testsuite.egg-info/dependency_links.txt
reading manifest file 'nose2_testsuite.egg-info/SOURCES.txt'
writing manifest file 'nose2_testsuite.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    test_suite='nose2.collector.collector',
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/omer/.virtualenvs/nose2-testsuite2.6/lib/python2.6/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/omer/.virtualenvs/nose2-testsuite2.6/lib/python2.6/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/home/omer/.virtualenvs/nose2-testsuite2.6/lib/python2.6/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib/python2.6/unittest.py", line 817, in __init__
    self.runTests()
  File "/usr/lib/python2.6/unittest.py", line 864, in runTests
    result = testRunner.run(self.test)
  File "/usr/lib/python2.6/unittest.py", line 753, in run
    test(result)
  File "/usr/lib/python2.6/unittest.py", line 464, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.6/unittest.py", line 460, in run
    test(result)
  File "/usr/lib/python2.6/unittest.py", line 464, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.6/unittest.py", line 460, in run
    test(result)
  File "/usr/lib/python2.6/unittest.py", line 300, in __call__
    return self.run(*args, **kwds)
  File "/home/omer/.virtualenvs/nose2-testsuite2.6/lib/python2.6/site-packages/nose2/collector.py", line 11, in run
    ok = self._collector(result_)
  File "/home/omer/.virtualenvs/nose2-testsuite2.6/lib/python2.6/site-packages/nose2/collector.py", line 21, in _collector
    ssn.loadPlugins(main.PluggableTestProgram.defaultPlugins)
AttributeError: type object 'PluggableTestProgram' has no attribute 'PluggableTestProgram'
```

**Comment by sirosen** [comment]
Closing as this is quite old and there's been more work on setuptools integration (thinking of #366).
Can be reopened or replaced if there are still issues with `setup.py test`.
